// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.0.3
//   protoc               v5.27.3
// source: proto/admins.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "admins";

export interface No {
}

export interface GetAdminProfileRequest {
  adminId: string;
}

export interface GetAdminProfileResponse {
  fullName: string;
  profilePic: string;
}

export interface AdminProfile {
  adminId: string;
  profilePic: string;
  fullName: string;
}

export interface GetAllAdminProfilesResponse {
  profiles: AdminProfile[];
}

export interface Admins {
  id: string;
  adminId: string;
  profilePic: string;
  fullName: string;
}

export const ADMINS_PACKAGE_NAME = "admins";

export interface AdminsProfileServiceClient {
  getAdminProfile(request: GetAdminProfileRequest): Observable<GetAdminProfileResponse>;

  getAllAdminsProfile(request: No): Observable<GetAllAdminProfilesResponse>;
}

export interface AdminsProfileServiceController {
  getAdminProfile(
    request: GetAdminProfileRequest,
  ): Promise<GetAdminProfileResponse> | Observable<GetAdminProfileResponse> | GetAdminProfileResponse;

  getAllAdminsProfile(
    request: No,
  ): Promise<GetAllAdminProfilesResponse> | Observable<GetAllAdminProfilesResponse> | GetAllAdminProfilesResponse;
}

export function AdminsProfileServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getAdminProfile", "getAllAdminsProfile"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AdminsProfileService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AdminsProfileService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ADMINS_PROFILE_SERVICE_NAME = "AdminsProfileService";
